# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.7

EAPI=8

CRATES="
	atty@0.2.14
	autocfg@1.1.0
	bitflags@1.3.2
	bumpalo@3.12.1
	cast@0.3.0
	cc@1.0.79
	cfg-if@1.0.0
	clap@2.34.0
	codespan-reporting@0.11.1
	criterion-plot@0.4.5
	criterion@0.3.6
	crossbeam-channel@0.5.8
	crossbeam-deque@0.8.3
	crossbeam-epoch@0.9.14
	crossbeam-utils@0.8.15
	csv-core@0.1.10
	csv@1.2.1
	cxx-build@1.0.94
	cxx@1.0.94
	cxxbridge-flags@1.0.94
	cxxbridge-macro@1.0.94
	either@1.8.1
	half@1.8.2
	hermit-abi@0.1.19
	hermit-abi@0.2.6
	indoc@1.0.9
	itertools@0.10.5
	itoa@1.0.6
	js-sys@0.3.61
	lazy_static@1.4.0
	libc@0.2.142
	link-cplusplus@1.0.8
	lock_api@0.4.9
	log@0.4.17
	memchr@2.5.0
	memoffset@0.8.0
	num-traits@0.2.15
	num_cpus@1.15.0
	once_cell@1.17.1
	oorandom@11.1.3
	parking_lot@0.12.1
	parking_lot_core@0.9.7
	plotters-backend@0.3.4
	plotters-svg@0.3.3
	plotters@0.3.4
	proc-macro2@1.0.56
	pyo3-build-config@0.18.3
	pyo3-ffi@0.18.3
	pyo3-macros-backend@0.18.3
	pyo3-macros@0.18.3
	pyo3@0.18.3
	quote@1.0.26
	rayon-core@1.11.0
	rayon@1.7.0
	redox_syscall@0.2.16
	regex-syntax@0.7.1
	regex@1.8.1
	ryu@1.0.13
	same-file@1.0.6
	scopeguard@1.1.0
	scratch@1.0.5
	serde@1.0.162
	serde_cbor@0.11.2
	serde_derive@1.0.162
	serde_json@1.0.96
	smallvec@1.10.0
	syn@1.0.109
	syn@2.0.15
	target-lexicon@0.12.7
	termcolor@1.2.0
	textwrap@0.11.0
	tinytemplate@1.2.1
	unicode-ident@1.0.8
	unicode-width@0.1.10
	unindent@0.1.11
	walkdir@2.3.3
	wasm-bindgen-backend@0.2.84
	wasm-bindgen-macro-support@0.2.84
	wasm-bindgen-macro@0.2.84
	wasm-bindgen-shared@0.2.84
	wasm-bindgen@0.2.84
	web-sys@0.3.61
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.45.0
	windows-targets@0.42.2
	windows_aarch64_gnullvm@0.42.2
	windows_aarch64_msvc@0.42.2
	windows_i686_gnu@0.42.2
	windows_i686_msvc@0.42.2
	windows_x86_64_gnu@0.42.2
	windows_x86_64_gnullvm@0.42.2
	windows_x86_64_msvc@0.42.2
"

DISTUTILS_EXT=1
DISTUTILS_USE_PEP517=maturin
PYTHON_COMPAT=( python3_{10..12} )
inherit cargo distutils-r1 pypi

DESCRIPTION="Python bindings for lzokay library"
HOMEPAGE="
	https://github.com/vlaci/lzallright
	https://pypi.org/project/lzallright
"
# sdist doesn't build (so didn't even get to check re tests)
SRC_URI="https://github.com/vlaci/lzallright/archive/refs/tags/v${PV}.tar.gz -> ${P}.gh.tar.gz"
SRC_URI+=" ${CARGO_CRATE_URIS}"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions MIT Unicode-DFS-2016
"
SLOT="0"
KEYWORDS="~amd64"

QA_FLAGS_IGNORED="usr/lib.*/py.*/site-packages/lzallright/_lzallright.*"

distutils_enable_tests pytest
